Fix `parent` type of string Unicode properties
eslint-community/regexpp pull request #127
Opened 2023-08-22 14:53 UTC by RunDevelopment

`StringsUnicodePropertyCharacterSet` allowed `ClassRangesCharacterClass` as their parent, which is not correct (see #123). This PR changes the `parent` type of `StringsUnicodePropertyCharacterSet` to remove ``ClassRangesCharacterClass``.

I also had to change the parser to get rid of type errors. Since we now have to prove that `parent` has a certain type, I had to change the code for `onUnicodePropertyCharacterSet` again. While having `parent.elements.push({ ...base, parent, strings, value, negate })` twice is code duplication, it's necessary for TS to prove that the types check out.

---

About why I used ``parent.elements.push({ ...base, parent, strings, value, negate })`` instead of `parent.elements.push({ ...base, parent, strings, value: null, negate: false })` in the `if (strings)` branch. By using the `value` and `negate` parameters instead of assigning the object properties a constant, TS forces us to validate the values of those 2 parameters.

This strict validation even unearthed a super minor bug. Calling `onUnicodePropertyCharacterSet` with a value of `""` (empty string) for string properties was previously accepted as valid (see `(strings && (negate || value))`). Now that TS forces us to validate `value` correctly, this is no longer the case.

2023-08-22 17:46 UTC, MichaelDeBoey requested changes

2023-08-22 17:46 UTC, MichaelDeBoey commented on src/parser.ts
>          }
What about refactoring this to

```suggestion
        if (strings && ((parent.type === "CharacterClass" && !parent.unicodeSets) ||
                negate ||
                value !== null)) {
            throw new Error("UnknownError")
        } else {
            parent.elements.push({ ...base, parent, strings, value, negate })
        }
```

2023-08-23 01:01 UTC, RunDevelopment commented on src/parser.ts
>          }
Doesn't type check. TS isn't smart enough for dependent types. Branching on `strings` if unfortunately necessary.

![image](https://github.com/eslint-community/regexpp/assets/20878432/18a44549-bc71-48cf-89c1-5f8b996a35eb)

2023-08-23 02:13 UTC, MichaelDeBoey commented on src/parser.ts
>          }
The `else` case isn't even necessary as the if-case will throw

Not sure if that makes TS happy though

2023-08-23 10:28 UTC, RunDevelopment commented on src/parser.ts
>          }
It certainly won't. TS's control flow analysis is smart enough to figure out that `if (cond) { throw X } else { foo() }` is equivalent to `if (cond) { throw X } foo()`.

2023-08-23 23:09 UTC, MichaelDeBoey approved these changes
I guess this is a breaking change, so we should release a new major version?

2023-08-24 01:40 UTC, ota-meshi commented
@MichaelDeBoey 
Why is this a breaking change? I think this is a minor change.

2023-08-24 08:41 UTC, RunDevelopment commented
Well, that depends on how you define a breaking change. If we say that any type change that results in TS compiler errors is a BC, then v4.6.0 (v flag) and v4.7.0 (#123) have also been BC.

Otherwise, this PR doesn't change the behavior of regexpp at all, aside from not allowing `value=""` anymore.

2023-08-24 11:03 UTC, ota-meshi commented
I don't think all of the type information changes are breaking changes.
If the behavior is breaking changed when running at runtime, I think it's a breaking change.
However, I think we might mark it as a breaking change if it fundamentally changes the type information.
So I don't think this PR change is a breaking change.

2023-08-24 21:03 UTC, MichaelDeBoey approved these changes
🚀

2023-08-25 07:03 UTC, merged