Export RegExpSyntaxError
eslint-community/regexpp pull request #144
Opened 2023-09-24 20:57 UTC by ArnaudBarre

2023-09-25 12:14 UTC, RunDevelopment commented
This would also export the [public constructor](https://github.com/eslint-community/regexpp/blob/97c3ce62367250ff8ae01e5322247e957aa247d9/src/regexp-syntax-error.ts#L6) of `RegExpSyntaxError`, which takes the internal type `RegExpValidatorSourceContext`. So this PR would also indirectly export `RegExpValidatorSourceContext` (e.g. via `ConstructorParameters<typeof RegExpSyntaxError>[0]`).

2023-09-26 02:46 UTC, ota-meshi commented
Yeah, I think we need to change the constructor to a factory method and not export the factory method from `index.ts`.

like:

```ts
export class RegExpSyntaxError extends SyntaxError {
    public index: number
}

export function newRegExpSyntaxError(
      srcCtx: RegExpValidatorSourceContext,
      flags: { unicode: boolean; unicodeSets: boolean },
      index: number,
      message: string,
  ): RegExpSyntaxError {
  // ...
}
```

2023-10-16 23:10 UTC, ArnaudBarre commented
Sorry the delay, I've updated the PR

2023-10-17 14:44 UTC, RunDevelopment commented on src/regexp-syntax-error.ts
>          message: string,
Maybe those should be the other way around? `message, index` feels more natural for errors to me. What do you think?

2023-10-17 16:35 UTC, ArnaudBarre commented on src/regexp-syntax-error.ts
>          message: string,
I hesitated, feel better to me to but that was the current order and minimized git diff. I can change it either just here or here and in the helper too

2023-10-18 11:31 UTC, RunDevelopment commented on src/regexp-syntax-error.ts
>          message: string,
I'm only concerned about the public error constructor, because it is part of the public API and can't be changed easily after merging this PR. I think having a good API is more important than minimizing git diff.

The helper function is okay as is IMO.

2023-10-22 00:16 UTC, MichaelDeBoey requested changes

2023-10-22 00:16 UTC, MichaelDeBoey commented on src/index.ts
> +import { RegExpSyntaxError } from "./regexp-syntax-error"
Since we're just doing an export and not using it in this file (like the other imports), we can simplify this to 

```suggestion
export { RegExpSyntaxError } from "./regexp-syntax-error"
```

2023-10-22 00:16 UTC, MichaelDeBoey commented on src/index.ts
> +export { AST, RegExpParser, RegExpValidator, RegExpSyntaxError }
```suggestion
export { AST, RegExpParser, RegExpValidator }
```

2023-10-25 14:26 UTC, ota-meshi approved these changes
LGTM!

2023-10-25 15:52 UTC, MichaelDeBoey approved these changes

2023-10-25 15:52 UTC, merged