feat: drop Node 8 & 10 support
eslint-community/regexpp pull request #16
Opened 2022-11-28 11:30 UTC by MichaelDeBoey

BREAKING CHANGE: Requires Node@^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0

2022-11-28 12:27 UTC, ota-meshi commented
Can we use `--legacy-peer-deps` to temporarily avoid the error?

2022-11-28 14:36 UTC, MichaelDeBoey commented
I'm wondering why we all of a sudden get these failures as we were already testing against these versions before 🤔

2022-12-28 10:35 UTC, ota-meshi commented
README.md also seems to have a description of the supported versions. Could you please correct this as well?

2022-12-28 10:50 UTC, ota-meshi approved these changes
👍

2022-12-28 15:43 UTC, voxpelli reviewed
Some thoughts

2022-12-28 15:43 UTC, voxpelli commented on .github/workflows/ci.yml
> +        node: [12.0.0, 12, 14.0.0, 14, 16.0.0, 16, 18.0.0, 18]
Could we add `19` as well while we're at it?

2022-12-28 15:43 UTC, voxpelli commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
Can we write this as `">=12.0.0"` instead? Or at least end with `>=18.0.0`?

Also, could we maybe opt for `^14.18.0 || >=16.0.0`? Then we will eg be able to use `node:` dependencies and use ESM dependencies (through `import()`)

Is there any specific reason to stay with Node 12?

2022-12-28 21:33 UTC, MichaelDeBoey commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
This package is used by `ESLint` core, & we want them to use this fork

Once they'll update their dependencies for v9, well update ours as well

2022-12-28 21:35 UTC, MichaelDeBoey commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
> Can we write this as `">=12.0.0"` instead?

I want to be explicit about the versions we support

> Is there any specific reason to stay with Node 12?

This package is used by ESLint core, & we want them to use this fork
Once they'll update their dependencies for v9, well update ours as well

2022-12-28 21:36 UTC, MichaelDeBoey commented on .github/workflows/ci.yml
> +        node: [12.0.0, 12, 14.0.0, 14, 16.0.0, 16, 18.0.0, 18]
Will do this in a separate PR 👍

2022-12-28 23:36 UTC, voxpelli commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
> I want to be explicit about the versions we support

Should definitely have `>=18.0.0` in there at least, else this will explicitly not support Node 19 (or any other future Node.js versions).

I would say that `engines.node` should indicate what _isn't_  supported rather than what is supported.

Eg. `^14.18.0 || >=16.0.0` is such a one: If one uses `node:` that's not supported in anything less (and not supported in `15.0`, so can not do a simple `>=14.18`)

If we know that we don't support anything less than `12.0.0` but should support everything above, then `>=12.0.0` is a good one.

That only test in LTS releases + latest is something we can convey elsewhere. If something works in eg. `12.0.0` and `14.0.0`, then its implied that it works in `13.0.0`

2022-12-28 23:37 UTC, voxpelli requested changes
I don't approve of `"node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"`

2022-12-29 00:51 UTC, MichaelDeBoey commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
Odd Node version numbers should only be used to test out packages, not in dev/production of something else

I'll add `>=18.0.0` to make you happy, but don't think we should include 13, 15 & 17

2022-12-29 11:47 UTC, ota-meshi commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
> This package is used by ESLint core, & we want them to use this fork

I think we should at least include `"node": "^12.22.0 || ^14.17.0 || >=16.0.0"` if we want to include it in ESLint v8. So I think we should specify `^12.0.0 || ^14.0.0 || >=16.0.0` in `engines.node`.

(I had not noticed that before. Thanks to this thread I realized that this package has a lot more to consider about the range of supported versions of Node than other plugins.)

2022-12-29 14:16 UTC, voxpelli commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
@MichaelDeBoey

> Odd Node version numbers should only be used to test out packages, not in dev/production of something else

Yes, that’s what the _Node_ team says, so it’s redundant for us to reiterate it.

We should simply state our _requirements_ and those are `>=12`

Anything else is out of scope for the `engine.node` field and causes issues when trying to calculate the combined minimum support for a package as it easily gets extremely verbose when combining everyone’s nitpickiness and personal opinions rather than explicit facts.

2022-12-29 15:16 UTC, voxpelli commented on package.json
> +    "node": "^12.0.0 || ^14.0.0 || ^16.0.0 || ^18.0.0"
I won't block on this if we add `>=18.0.0` to the end though

2022-12-30 18:02 UTC, voxpelli approved these changes

2022-12-30 18:54 UTC, merged