chore(deps-dev): update `@mysticatea/eslint-plugin` to `@eslint-community/eslint-plugin-mysticatea`
eslint-community/regexpp pull request #31
Opened 2022-12-28 10:50 UTC by MichaelDeBoey

2023-01-05 03:11 UTC, ota-meshi requested changes

2023-01-05 03:11 UTC, ota-meshi commented on src/validator.ts
> +        return Boolean(this._options.strict ?? this._uFlag)
This change should be revert. I think it's probably a typescript-eslint false positive.

2023-01-05 06:40 UTC, MichaelDeBoey commented on src/validator.ts
> +        return Boolean(this._options.strict ?? this._uFlag)
I don't think it is 🤔

If `strict` is set to `false`, I don't think we should look into `_uFlag`?

2023-01-05 08:03 UTC, ota-meshi requested changes

2023-01-05 08:03 UTC, ota-meshi commented on src/validator.ts
> +        onLiteralEnter: (start: number) => void
I think we need to put the `?` back.

```suggestion
        onLiteralEnter?: (start: number) => void
```

2023-01-05 08:06 UTC, ota-meshi commented on src/visitor.ts
> +        onAlternativeEnter: (node: Alternative) => void
```suggestion
        onAlternativeEnter?: (node: Alternative) => void
```

2023-01-05 15:24 UTC, MichaelDeBoey commented on src/validator.ts
> +        return Boolean(this._options.strict ?? this._uFlag)
Then it should be `this._uFlag ?? this._options.strict` instead?

2023-01-05 23:31 UTC, ota-meshi commented on src/validator.ts
> +        return Boolean(this._options.strict ?? this._uFlag)
No. We should use the `||` operator instead of the `??` operator.

```suggestion
        return Boolean(this._options.strict) || this._uFlag
```

If `Boolean(this._options.strict)` is true, parse without using Annex B.
That is, parse strictly. For example `/{/` is a syntax error. (`/{/` is not a syntax error in the Annex B specification.)

If `this._uFlag` is true, the unicode flag is used. That is, parse strictly. For example `/{/u` is a syntax error (whether or not you use Annex B).

2023-01-13 21:31 UTC, ota-meshi approved these changes
LGTM! Thank you!

2023-01-13 21:31 UTC, merged