feat: support for Unicode properties Script Values added in ES2022
eslint-community/regexpp pull request #6
Opened 2022-11-28 02:18 UTC by ota-meshi

2023-01-13 23:43 UTC, MichaelDeBoey requested changes

2023-01-13 23:43 UTC, MichaelDeBoey commented on scripts/update-unicode-properties.ts
> +        url: "https://tc39.es/ecma262/2022/multipage/text-processing.html",
I think it would be better to keep these all uniform, no?

```suggestion
        url: "https://262.ecma-international.org/13.0",
```

2023-01-13 23:49 UTC, ota-meshi commented on scripts/update-unicode-properties.ts
> +        url: "https://tc39.es/ecma262/2022/multipage/text-processing.html",
Referencing multipage costs less to finishes faster. So I want to refer to multipage.
I would like to unify others, but there is no multipage before ES2021 😢

2023-01-14 00:00 UTC, MichaelDeBoey commented on scripts/update-unicode-properties.ts
> +        url: "https://tc39.es/ecma262/2022/multipage/text-processing.html",
OK let's go with `multipage` as of ES2021 then! 👍

2023-01-14 00:08 UTC, MichaelDeBoey approved these changes

2023-01-14 00:09 UTC, merged