fix: add `types` condition to the front of the `exports`
eslint-community/regexpp pull request #85
Opened 2023-04-29 14:19 UTC by Andarist

Reopening https://github.com/mysticatea/regexpp/pull/30 here as suggested by @MichaelDeBoey

2023-04-29 14:21 UTC, MichaelDeBoey requested changes
@Andarist Could you please rebase your branch onto latest `main` & resolve conflicts?

2023-04-29 14:25 UTC, Andarist commented
@MichaelDeBoey done

2023-04-29 14:26 UTC, MichaelDeBoey approved these changes

2023-04-30 01:33 UTC, ota-meshi approved these changes

2023-04-30 01:33 UTC, merged